
<!DOCTYPE BlogPosts [
<!ELEMENT BlogPosts (BlogPost)+>
<!ELEMENT BlogPost (date, topic, title, author, content, scripture, prayer?)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT topic (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT content (#PCDATA)>
<!ELEMENT scripture (#PCDATA)>
<!ELEMENT prayer (#PCDATA)>
]>
<BlogPosts>
    <BlogPost>
      <date> October 29, 2018</date>
      <topic>Prodigals</topic>
      <title> Praying for the Prodigal</title>
      <author>Patricia van der Merwe</author>
      <content>article body</content>
      <scripture>Bible reference</scripture>
      <prayer>prayer</prayer>
    </BlogPost>

   <BlogPost>
      <date>November 24, 2018</date>
      <topic>Generational Curses</topic>
      <title>What's in my Family Line?</title>
      <author>Katharine Gruber</author>
      <content>My fondest memories of my Grandpa, my mom’s dad, began around age four. That’s the year my family moved from Wisconsin back to Minnesota. I recently asked my Dad why we moved to Minnesota. Nothing prepared me for his response, for I hadn’t considered I could be the reason.
In the 1960’s, women’s treatment in the work place differed from men. My father, a math, chemistry, and physics teacher, taught High School in a small town in the middle of Wisconsin. When he accepted and signed his contract, there were no conditions or stipulations that he needed to work one year before he quit, moved or accepted a new job due to family.
Mom, on the other hand, was required to not get pregnant during her first-year of teaching. I have never signed a work contract that stipulated family planning as a condition for employment. That part of her contract was broken. I arrived that July between her first and second year of teaching.
My parents didn’t have family close by, so I was cared for by a family friend. At six-weeks old, I contracted my first childhood illness—chicken pox. Welcome to the benefits and liabilities of day care. Mom said I was the youngest case of chicken pox the doctor had ever treated. Other illnesses followed with increasing doctor bills and not having enough money to pay for them.
Grandpa
My dad found a teaching position located in a suburb south of St. Paul. He made enough money for my mom to quit teaching full-time and take care of me. I would be turning four that summer between school terms. They purchased their first new home that year, and to save money, they painted the inside of the house themselves. During their two weeks of painting, I lived with my mom’s parents.
I loved my mom’s parents. Grandma let me help make cookies, took me with her shopping, and introduced me to gardening. My grandpa wasn’t kind and sweet like my grandma. No, he’d walk around the corner of the living room singing little ditties, as he called them. His favorites were “Oh My Darlin’ Clementine” and another one about Phineas Fogg. He was loud, and kind of scary if I did something wrong. He’d raise his voice and yell “Yaaah,” assume a boxing stance and pretend to take a swipe, scaring and distracting me. I sensed his pent-up anger and began to walk on egg shells around him. Other times he was playful and would gently tweak my nose and pretend to pull it off, or reach behind my ear and open his hand to give me a quarter. That was a large sum of money for a four-year-old. He’d tell me not to spend it all in one place.
As I grew older, I noted why I felt scared around my grandpa. Every afternoon between lunch and supper, my grandfather indulged in gin and tonics. I noticed after his second or third drink, he’d say mean things, his eyes watered and looked bloodshot. Pity the unsuspecting person who dared to disagree with him on any topic. He’d raise his voice and verbally shut them down. I learned to keep my opinions to myself.
 When my great grandmother moved in with them, there’d be strong disagreements on politics. My grandmother did the best she could to restore peace but to little avail. Family dinners consisted of Grandpa’s verbal tirades then him succumbing to choking/coughing jags that ended the verbal battles. Everyone froze, waiting to see if he’d recover—he did.
Awareness
Mealtime cleanup created the perfect environment to learn the ins and outs of family members’ lives. Washing dishes wasn’t my favorite thing to do except during family get- togethers. After meals the men and boys walked outside or gathered in the living room to talk about cars, weather, and more politics. Topics I didn’t care about. The kitchen is where I learned about other relatives with drinking problems, who had been diagnosed with cancer or high blood pressure, which cousin had a baby out-of-wedlock, and so forth. I noticed there were patterns to certain illnesses and addictions that repeated through the generations. Would these patterns repeat in my life and those of my children? Could anything be done?
To be continued...</content>
      <scripture>Exodus 20:5; Numbers 14:18; Deuteronomy 5:9-10;</scripture>
      <prayer>Dear Heavenly Father, I thank you that you sent your Son to die on the cross for me. In doing this, you freed me from the power of sin and death over my life. I renounce the curse of addiction that has traveled down my family line.
      I cancel its assignment over my family and thank you for your love and freedom. I plead the blood of Jesus over my generational line. In the name of Jesus I pray. Amen.</prayer>
    </BlogPost>
  </BlogPosts>
